[web]
listen = ":80"

[db]
user = "iot"
password = "thingple"
host = "192.168.10.32"
port = 5432
database = "owl_messager"
ssl = "disable" #require/verify-full/verify-ca/disable

[token]
issuer = "domain.com.cn"
key = "1234asdfrtyuedcvtainch@r&y%ttghu"
enable = true