name: Docker Image CI

on:
  push:
    tags: [ "v*" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        ./build.sh
    - name: Push
      run: |
        docker version
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
        ./build.sh push
